feat: add target to create storage user secret

diff --git a/k8s/Makefile b/k8s/Makefile
--- a/k8s/Makefile
+++ b/k8s/Makefile
@@ -302,11 +302,31 @@ elasticsearch-exporter-delete: _env-check ## Delete Prometheus Elasticsearch Exp
 ################################################################################
 
 MINIO_OPERATOR_VERSION := 7.1.1
+MINIO_CONSOLE_ACCESS_KEY ?= consoleaccess
+MINIO_CONSOLE_SECRET_KEY ?= consolesecret
 
 .PHONY: minio-operator-deploy
 minio-operator-deploy: _env-check ## Install MinIO Operator using Kustomize
 	@echo "Installing MinIO Operator v$(MINIO_OPERATOR_VERSION)..."
 	@kubectl kustomize github.com/minio/operator\?ref=v$(MINIO_OPERATOR_VERSION) | kubectl apply -f -
+
+.PHONY: minio-storage-user-secret-create
+minio-storage-user-secret-create: _env-check ## Create/update MinIO Console credentials secret. Usage: make minio-storage-user-secret-create SVC_NAME=<svc-name> MINIO_CONSOLE_ACCESS_KEY=<access-key> MINIO_CONSOLE_SECRET_KEY=<secret-key>
+	@if [ -z "$$SVC_NAME" ]; then \
+	   echo "Argument 'SVC_NAME' is required!"; \
+	   exit 1; \
+	fi
+	@NAMESPACE="$(ENV_NAME)-minio-$$SVC_NAME"; \
+	SECRET_NAME="$$NAMESPACE-storage-user-creds"; \
+	kubectl get namespace "$$NAMESPACE" >/dev/null 2>&1 || kubectl create namespace "$$NAMESPACE"; \
+	echo "Creating MinIO Console credentials secret in namespace $$NAMESPACE..."; \
+	kubectl create secret generic "$$SECRET_NAME" \
+	   --namespace "$$NAMESPACE" \
+	   --type Opaque \
+	   --from-literal=CONSOLE_ACCESS_KEY="$(MINIO_CONSOLE_ACCESS_KEY)" \
+	   --from-literal=CONSOLE_SECRET_KEY="$(MINIO_CONSOLE_SECRET_KEY)" \
+	   --dry-run=client -o yaml | kubectl apply -f -; \
+	echo "Secret '$$SECRET_NAME' successfully created/updated in namespace $$NAMESPACE"
 
 ################################################################################
 # MongoDB Deployment Targets
