finalize targets for building all legacy artifacts and deploying it to local dev cluster

diff --git a/k8s/Makefile b/k8s/Makefile
--- a/k8s/Makefile
+++ b/k8s/Makefile
@@ -957,3 +957,98 @@ svc-delete: _env-check _svc-name-check ## Delete (purge) a deployed Java service
 
 .PHONY: svc-load-delete-deploy
 svc-load-delete-deploy: _env-check _svc-ns-check _svc-name-check svc-image-local-dev-load svc-delete svc-deploy ## Load Docker image, delete and deploy a Java service or web app using Kustomize. Usage: make svc-load-delete-deploy SVC_NAME=<svc-name>
+
+##############################################################################################
+# Local Dev Cluster Infra and Services Deployment Targets
+# Targets for deploying and managing Insurance Hub infra and service apps in local dev cluster
+##############################################################################################
+
+.PHONY: legacy-all-build
+legacy-all-build: ## Build all legacy artifacts sequentially (Java → Frontend → Docker). Usage: legacy-all-build
+	@echo "🚀 Building all legacy artifacts (Java → Frontend → Docker)..."
+
+	$(MAKE) java-all-build
+	$(MAKE) frontend-build
+	$(MAKE) docker-frontend-build
+	$(MAKE) docker-java-svc-all-build
+	@docker images | grep insurance-hub
+
+	@echo "✅ Legacy all legacy artifacts build completed!"
+	@echo "📦 Ready for k8s deployment!"
+
+.PHONY: local-dev-infra-deploy
+local-dev-infra-deploy: _env-check ## Deploy all infra apps into local dev Kind cluster. Usage: make local-dev-infra-deploy
+	@echo "🚀 Deploying local-dev infra apps (all optional args omitted)..."
+	@if [ "$(ENV_NAME)" != "local-dev" ]; then \
+		echo "ERROR: This target is only applicable for the 'local-dev' environment."; \
+		exit 1; \
+	fi
+
+	# Infra operators
+	$(MAKE) es-operator-deploy & \
+	$(MAKE) postgres-operator-deploy & \
+	$(MAKE) minio-operator-deploy & \
+	$(MAKE) mongodb-operator-install & \
+	$(MAKE) kafka-strimzi-operator-install & wait
+	@echo "⏳ Waiting 15s for infra operators..." && sleep 15
+
+	# Elasticsearch
+	$(MAKE) es-deploy
+
+	# Postgres
+	@POSTGRES_SVC_NAMES="auth,document,payment,policy,pricing,product" ; \
+	POSTGRES_SVC_NAMES=$$(echo "$$POSTGRES_SVC_NAMES" | tr ',' ' ') ; \
+	for svc in $$POSTGRES_SVC_NAMES ; do \
+		$(MAKE) postgres-svc-secret-create SVC_NAME=$$svc ; \
+		$(MAKE) postgres-svc-deploy SVC_NAME=$$svc ; \
+	done ;
+
+	# MongoDB
+	$(MAKE) mongodb-root-user-secret-create
+	$(MAKE) mongodb-product-user-secret-create
+	$(MAKE) mongodb-deploy
+
+	# Kafka
+	$(MAKE) kafka-deploy
+
+	# MinIO Tenants
+	$(MAKE) minio-storage-user-secret-create SVC_NAME=document
+	$(MAKE) minio-storage-config-secret-create SVC_NAME=document
+	$(MAKE) minio-storage-user-secret-create SVC_NAME=payment
+	$(MAKE) minio-storage-config-secret-create SVC_NAME=payment
+	$(MAKE) minio-tenant-deploy SVC_NAME=document & $(MAKE) minio-tenant-deploy SVC_NAME=payment & wait
+	@echo "⏳ Waiting 3m for MinIO tenants.." && sleep 180
+
+	# MinIO Tenant Configuration
+	# Document
+	$(MAKE) minio-svc-bucket-create SVC_NAME=document BUCKET_NAME=policies
+	$(MAKE) minio-svc-user-secret-create SVC_NAME=document
+	$(MAKE) minio-svc-user-with-policy-create SVC_NAME=document POLICY_FILE=apps/svc/document/minio/s3-policy-policies.json
+	# Payment
+	$(MAKE) minio-svc-bucket-create SVC_NAME=payment BUCKET_NAME=payments-import
+	$(MAKE) minio-svc-user-secret-create SVC_NAME=payment
+	$(MAKE) minio-svc-user-with-policy-create SVC_NAME=payment POLICY_FILE=apps/svc/payment/minio/s3-policy-payments-import.json
+
+	@echo "✅ Infra apps deployed to local-dev cluster!"
+	@kubectl get pods -A | grep -E "local-dev-all|minio|elastic|kafka|cnpg"
+
+.PHONY: local-dev-svc-deploy
+local-dev-svc-deploy:  _env-check ## Deploy all services into local dev Kind cluster. Usage: make local-dev-svc-deploy
+	@echo "🚀 Deploying local-dev services..."
+	@if [ "$(ENV_NAME)" != "local-dev" ]; then \
+		echo "ERROR: This target is only applicable for the 'local-dev' environment."; \
+		exit 1; \
+	fi
+
+	$(MAKE) jsreport-deploy
+
+	@SVC_NAMES="web-vue,agent-portal-gateway,auth,product,policy-search,dashboard,policy,pricing,document,payment,chat" ; \
+	SVC_NAMES=$$(echo "$$SVC_NAMES" | tr ',' ' ') ; \
+	for svc in $$SVC_NAMES ; do \
+		$(MAKE) svc-load-delete-deploy SVC_NAME=$$svc ; \
+	done
+	@echo "⏳ Waiting 60s for services..." && sleep 60
+
+	@echo "✅ Service apps deployed to local-dev cluster!"
+	@kubectl get pods | grep -E "web|agent|api"
+	@kubectl top pods | grep -E "web|agent|api"
